# Generated by Django 5.2 on 2025-11-07 00:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rendimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_mesa', models.PositiveIntegerField(verbose_name='Número de mesa')),
                ('variedad', models.CharField(max_length=100)),
                ('medida', models.CharField(max_length=50)),
                ('bonches', models.PositiveIntegerField()),
                ('fecha_entrada', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('rendimiento', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
