# Generated by Django 5.2 on 2025-11-07 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rendimiento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendimiento',
            name='rendimiento',
        ),
    ]
