# Generated by Django 5.2 on 2025-11-23 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rendimiento', '0002_remove_rendimiento_rendimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendimiento',
            name='codigo_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
