# Generated by Django 6.0 on 2025-12-23 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rendimiento', '0003_rendimiento_codigo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendimiento',
            name='codigo_id',
        ),
    ]
