# Generated by Django 6.0 on 2025-12-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rendimiento', '0004_remove_rendimiento_codigo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendimiento',
            name='qr_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
