# Generated by Django 6.0 on 2025-12-31 13:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rendimiento', '0005_rendimiento_qr_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRUsado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_id', models.CharField(max_length=255, unique=True)),
                ('fecha_escaneo', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='rendimiento',
            name='bonches',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='rendimiento',
            name='fecha_entrada',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rendimiento',
            name='numero_mesa',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rendimiento',
            name='qr_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
