# Generated by Django 6.0 on 2026-01-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rendimiento', '0006_qrusado_alter_rendimiento_bonches_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rendimiento',
            old_name='fecha_salida',
            new_name='hora_final',
        ),
        migrations.RemoveField(
            model_name='rendimiento',
            name='medida',
        ),
        migrations.RemoveField(
            model_name='rendimiento',
            name='variedad',
        ),
        migrations.AddField(
            model_name='rendimiento',
            name='extras_por_hora',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rendimiento',
            name='hora_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rendimiento',
            name='horas_trabajadas',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rendimiento',
            name='ramos_base',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rendimiento',
            name='ramos_esperados',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rendimiento',
            name='ramos_extras',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rendimiento',
            name='rendimiento',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rendimiento',
            name='bonches',
            field=models.IntegerField(default=0),
        ),
    ]
