# Generated by Django 5.2.4 on 2026-01-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rendimiento', '0007_rename_fecha_salida_rendimiento_hora_final_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JornadaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_username', models.CharField(max_length=150)),
                ('usuario_nombre', models.CharField(max_length=100)),
                ('mesa', models.CharField(max_length=100)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora_inicio', models.DateTimeField()),
                ('hora_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('iniciada', 'Jornada Iniciada'), ('finalizada', 'Jornada Finalizada')], default='iniciada', max_length=20)),
                ('horas_trabajadas', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fecha', '-hora_inicio'],
                'unique_together': {('usuario_username', 'fecha')},
            },
        ),
    ]
