# Generated by Django 6.0 on 2026-01-16 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rendimiento', '0008_jornadalaboral'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JornadaLaboral',
        ),
    ]
