# Generated by Django 5.2.4 on 2026-01-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rendimiento', '0010_alter_rendimiento_fecha_entrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendimiento',
            name='fecha_entrada',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rendimiento',
            name='rendimiento',
            field=models.IntegerField(default=0),
        ),
    ]
