# Generated by Django 6.0 on 2025-12-14 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_mesa', models.PositiveIntegerField(verbose_name='Número de mesa')),
                ('variedad', models.CharField(max_length=100)),
                ('medida', models.CharField(max_length=50)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('fecha_entrada', models.DateTimeField()),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
