# Generated by Django 6.0 on 2026-01-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Disponibilidad', '0002_qrdisponibilidadusado'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRDisponibilidadSalidaUsado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_id', models.CharField(max_length=255, unique=True)),
                ('fecha_escaneo', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
