# Generated by Django 6.0 on 2026-01-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Disponibilidad', '0003_qrdisponibilidadsalidausado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
